# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pokedex

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-deps:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Pokedex Repository
        uses: actions/checkout@v4
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          # Crea un candado único basado en la versión de Node y tu package-lock
          key: node-modules-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        # Solo instala si la caché no existía para esta versión
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm install --no-fund --no-audit
  unit-test:
    needs: install-deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          # Usa exactamente la misma llave para descargar la carpeta guardada en JOB 1
          key: node-modules-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
      - name: Run unit tests
        run: npm run test

      - name: Save coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage
